<a href="https://colab.research.google.com/github/bugeki/workshops/blob/main/Pandas_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [2]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
np.ones((4,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
np.ones((4,4),dtype="int")*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,dtype=int,num=25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.randn(5)

array([ 0.71084597, -1.26155781, -0.47899606, -0.12329595, -0.29878418])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.randn(5,5)

array([[-0.99040297,  0.74440909, -1.02002549, -0.13264656, -0.2604177 ],
       [ 0.46210531,  1.05136728, -0.87175495, -1.7644818 , -0.86121067],
       [-0.2891003 , -0.10937359, -0.82378697, -0.08210688,  0.53761903],
       [ 0.39951878, -0.06505634, -2.1734264 , -0.94254712, -0.98464931],
       [ 1.07115295, -2.14408151, -0.33019564, -0.0403265 ,  0.2741978 ]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [3]:
np.random.randint(20,50,12).reshape(3,4)

array([[29, 31, 25, 43],
       [43, 43, 32, 48],
       [45, 41, 34, 41]])

#### 13. Reshape the array below with shape 6x8

In [4]:
np.random.randint(1,50,48)

array([21,  7, 45, 20, 20, 23, 43, 42, 13, 15, 25, 32, 47, 12, 48,  1, 38,
       49, 23, 38, 25, 32, 26, 20,  5, 28, 31, 47, 28,  6, 27, 40, 20, 48,
       31,  6, 29, 49, 43, 10, 39, 29, 24, 36,  6, 21,  6, 16])

In [7]:
ranarr = np.random.randint(1,50,48)
ranarr
ranarr.reshape(6,8)

array([[14,  6, 16, 13, 18, 39, 30, 13],
       [41,  9, 25, 44, 43, 14, 28,  5],
       [25, 48, 44, 30, 37, 18, 26, 21],
       [27, 16, 21, 37, 16, 19, 47, 46],
       [42, 35, 26, 34, 16, 22, 28,  2],
       [21, 22,  4, 25, 17,  9, 41, 19]])

In [9]:
ranarr.reshape(-1,12)

array([[14,  6, 16, 13, 18, 39, 30, 13, 41,  9, 25, 44],
       [43, 14, 28,  5, 25, 48, 44, 30, 37, 18, 26, 21],
       [27, 16, 21, 37, 16, 19, 47, 46, 42, 35, 26, 34],
       [16, 22, 28,  2, 21, 22,  4, 25, 17,  9, 41, 19]])

In [ ]:
#reshape with -1


array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [49]:
#Create array below
mat= np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [50]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [51]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [60]:
mat[1,::2]

array([ 5, 77])

#### 17.Assign 77 to every cell in 3rd column.

In [53]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [61]:
mat[[1,3],[0,1]] ## burada rowlar ve columnlar grup olarak iç parantezlerde yazıldı

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [59]:
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [62]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [68]:
mat[mat<10]


array([1, 2, 4, 5, 6, 8, 9])

In [69]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [70]:
mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [71]:
np.std(mat[mat<10] + mat[mat>12])

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [76]:
mat[:,1].sum()

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[2]

array([ 9, 10, 11, 12])

In [78]:
#median
np.median(mat[2])

11.0

In [79]:
#mean
np.median(mat[2])

11.0

In [80]:
#std
np.std(mat[2])

28.88771365130858

# Pandas Section

In [2]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [5]:
sal=pd.read_csv('/content/sample_data/Salaries.csv')  ### dosyayı yükleyince adresini böyle gireceğiz

In [84]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [ ]:
sal.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [ ]:
#max
sal.TotalPay.max()

567595.43

In [ ]:
#avg
sal.TotalPay.mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
len(sal[sal.TotalPay>sal.TotalPay.mean()])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [89]:
sal[sal['EmployeeName'] == "ALBERT PARDINI"].TotalPayBenefits

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [95]:
sal[sal['EmployeeName'] == "ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [98]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()].EmployeeName

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [102]:
sal[sal.TotalPayBenefits == sal.TotalPayBenefits.min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [103]:
sal.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [106]:
sal.JobTitle.value_counts().tail(3)

SHELTER OFFICE ASSISTANT SUPERVISOR                   1
HEAD AIRPORT ELECTRICIAN                              1
CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC SAFE    1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [22]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.mean()) & (sal.Year == 2012)]["EmployeeName"].count()

20366

**How many people have the word Manager in their job title?**

In [ ]:
sum(sal['JobTitle'].apply(lambda x:"manager" in x.lower()))

In [32]:
#use apply function here
len(sal[sal.JobTitle.apply(lambda x : True if "manager" in x.lower() else False)])

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [41]:
sal_new = sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [42]:
sal_new= sal_new.loc[:,"EmployeeName":"TotalPayBenefits"]
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [48]:
sal[(sal.TotalPayBenefits< sal.TotalPayBenefits.mean()) & (sal.TotalPayBenefits > sal.TotalPayBenefits.min())]["EmployeeName"]

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object